---

- name: 'Provision Image using Ansible'
  hosts: default
  become: true


  handlers:
    - name: restart apache
      service:
        name: "apache2"
        state: restarted

  tasks:
    - name: Ensure Apache is installed.
      package:
        name: 'apache2'
        state: present

    - name: Ensure Apache is running and starts at boot.
      service:
        name: "apache2"
        state: started
        enabled: true
