---

- name: 'Provision Image using Ansible'
  hosts: all
  become: true
  become_method: sudo


  handlers:
    - name: restart apache
      service:
        name: "apache2"
        state: restarted

  tasks:
    - name: Update and upgrade apt packages
      package:
        upgrade: true
        update_cache: true
        cache_valid_time: 259200 # three days

    - name: Ensure Apache is installed.
      package:
        name: 'apache2'
        state: present

    - name: Ensure Apache is running and starts at boot.
      service:
        name: "apache2"
        state: started
        enabled: true
